# Generated by Django 4.0.5 on 2022-07-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_post_categoria_post_ingredientes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='post',
            name='ingredientes',
            field=models.CharField(max_length=20),
        ),
    ]
