# Generated by Django 4.0.5 on 2022-07-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0006_remove_post_categoria_alter_post_ingredientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ingredientes',
            field=models.TextField(),
        ),
    ]
