# Generated by Django 4.0.5 on 2022-07-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0008_alter_post_ingredientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='porciones',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='tiempo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
